security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity: { class: App\Entity\User, property: email }

  role_hierarchy:
    ROLE_MANAGER: [ROLE_USER]
    ROLE_ADMIN:   [ROLE_MANAGER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]

  firewalls:
    dev: { pattern: ^/(_(profiler|wdt)|css|images|js)/, security: false }
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: /dashboard
        username_parameter: email
        password_parameter: password
        enable_csrf: true
      logout: 
        path: app_logout
        target: app_login  # ✅ Ajout de la redirection après logout

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/lock, roles: PUBLIC_ACCESS }        # ✅ Ajout pour lock screen
    - { path: ^/unlock, roles: PUBLIC_ACCESS }      # ✅ Ajout pour unlock
    - { path: ^/test, roles: ROLE_USER }            # ✅ Ajout pour vos tests
    - { path: ^/user, roles: ROLE_ADMIN }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/prestation, roles: ROLE_ADMIN }
    - { path: ^/cash/categories, roles: ROLE_ADMIN }
    - { path: ^/deposit/delete, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/rdv, roles: ROLE_USER }
    - { path: ^/payment, roles: ROLE_USER }